
debug

set "template_path" "../../spright/templates/"
template "{{template_path}}css.inja"
description "spright.css"

pack columns
trim none
set "style" "display: inline-block;"

sheet "icons"
  id "{{ source.filenameId }}"
  glob icons/*.png
  output "icons.spright.png"

sheet "paper"
  id "{{ source.filenameId }}_{{ inputSpriteIndex }}"
  atlas
  input Paper.png
  output "paper.spright.png"
