debug

pack rows
padding 1

sheet "red"
  output "red.png"
  
sheet "green"
  max-width 100
  output "green.png"

sheet "blue"
  pack columns
  output "blue.png"

colorkey
crop
crop-pivot

input "Old enemies 2.png"
  sheet "blue"
  grid 16 16
    tag anim "blue_enemy_idle"
    sprite
    sprite
    tag anim "blue_enemy_dead"
    sprite
    tag anim "blue_enemy_jump"
    sprite
  row 1
    tag anim "blue_enemy_run"
    sprite
    sprite
    sprite
    sprite
    sprite
    sprite
  sheet "red"
  row 2
    tag anim "red_enemy_idle"
    sprite
    sprite
    tag anim "red_enemy_dead"
    sprite
    tag anim "red_enemy_jump"
    sprite  
  row 3
    tag anim "red_enemy_run"
    sprite
    sprite
    sprite
    sprite
    sprite
  sheet "green"
  row 4
    tag anim "green_enemy_idle"
    sprite
    sprite
    tag anim "green_enemy_dead"    
    sprite
    tag anim "green_enemy_jump"
    sprite
  row 5
    tag anim "green_enemy_run"
    sprite
    sprite
    sprite
    sprite
    sprite
    sprite
