debug

scale 4

sheet "png"
  output "spright.png"
    pack rows

colorkey
grid 16 16
min-bounds 24
crop-pivot

input "Old enemies 2.png"
  sprite
    align center bottom
  sprite
    align top + 2, right - 2
  sprite
    align center + 1, middle + 1