debug

sheet "sprites"
  padding 10
  output "spright-{0-}.png"
  
transform Rotate2x
  resize 4.0
  rotate 45
  resize 0.5

input "misc_scenery.png"
  sprite "candles"
    rect 25 18 17 51
  sprite "cage"
    rect 44 8 32 77
  duplicate "cage45"
    rotate 45
  duplicate "candles45" "candles"
    rotate 45

  # rotate already rotated duplicate with complex transformation
  transform Rotate2x
  duplicate "cage90" "cage45"

