debug

scale 4
padding 4

sheet "png"
  output "spright.png"
    pack rows
    max-width 170
    
sheet "gif"
  output "spright.gif"
    pack layers
    alpha colorkey FF00FF

colorkey
grid 16 16
common-bounds
align center bottom
crop-pivot

input "Old enemies 2.png"
  sheet "png"

input "Old enemies 2.png"
  sheet "gif"
